#!/usr/bin/env python3
"""
Generate FREE Falcon (ternary N=1536) and FrodoKEM-640-SHAKE KAT vectors.

Python (libff_falcon.so + liboqs) generates keys, signatures, KEM operations.
C (vendor/falcon Extra/c + liboqs) must produce identical results.

Vectors:
  1. Falcon keygen: same seed -> same pk/sk
  2. Falcon sign:   Python signs -> C must verify
  3. Falcon sign:   second message -> second sig -> C must verify
  4. FrodoKEM:      Python keygen + encaps -> C decaps -> same shared secret
  5. FrodoKEM:      second encaps -> second ct/ss -> C decaps matches

Usage:
    python3 gen_falcon_frodo_kat.py > falcon_frodo_kat_vectors.h
"""

import ctypes
import os
import sys
import warnings

warnings.filterwarnings("ignore")
import oqs  # noqa: E402

# FREE Falcon ternary sizes (N=1536, q=18433, logn=10, Huffman compression)
FALCON_PK_SIZE = 2881
FALCON_SK_SIZE = 7681
FALCON_SIG_MAX_SIZE = 2000

_lib_path = os.path.join(os.path.dirname(__file__), "..", "..", "server", "app", "crypto", "native", "libff_falcon.so")
_lib = ctypes.CDLL(_lib_path)
_lib.ff_free_falconb_sign_keygen.argtypes = [ctypes.c_void_p, ctypes.c_size_t,
                                              ctypes.c_void_p, ctypes.c_size_t,
                                              ctypes.c_void_p, ctypes.c_size_t]
_lib.ff_free_falconb_sign_keygen.restype = ctypes.c_int
_lib.ff_free_falconb_sign_sign_ct.argtypes = [ctypes.c_void_p, ctypes.c_size_t,
                                               ctypes.c_void_p, ctypes.c_size_t,
                                               ctypes.c_void_p, ctypes.c_size_t,
                                               ctypes.c_void_p, ctypes.c_size_t]
_lib.ff_free_falconb_sign_sign_ct.restype = ctypes.c_int
_lib.ff_free_falconb_sign_verify.argtypes = [ctypes.c_void_p, ctypes.c_size_t,
                                              ctypes.c_void_p, ctypes.c_size_t,
                                              ctypes.c_void_p, ctypes.c_size_t]
_lib.ff_free_falconb_sign_verify.restype = ctypes.c_int


def falcon_keygen(seed: bytes):
    pk = bytearray(FALCON_PK_SIZE)
    sk = bytearray(FALCON_SK_SIZE)
    rc = _lib.ff_free_falconb_sign_keygen(seed, len(seed),
                                           (ctypes.c_ubyte * FALCON_SK_SIZE).from_buffer(sk), FALCON_SK_SIZE,
                                           (ctypes.c_ubyte * FALCON_PK_SIZE).from_buffer(pk), FALCON_PK_SIZE)
    assert rc == 0, f"falcon keygen failed: {rc}"
    return bytes(pk), bytes(sk)


def falcon_sign(seed: bytes, sk: bytes, msg: bytes):
    sig = bytearray(FALCON_SIG_MAX_SIZE)
    rc = _lib.ff_free_falconb_sign_sign_ct(seed, len(seed),
                                            sk, len(sk),
                                            msg, len(msg),
                                            (ctypes.c_ubyte * FALCON_SIG_MAX_SIZE).from_buffer(sig), FALCON_SIG_MAX_SIZE)
    assert rc == 0, f"falcon sign failed: {rc}"
    return bytes(sig)


def falcon_verify(pk: bytes, msg: bytes, sig: bytes):
    rc = _lib.ff_free_falconb_sign_verify(pk, len(pk), msg, len(msg), sig, len(sig))
    return rc == 0


# FrodoKEM via liboqs

KEM_ALG = "FrodoKEM-640-SHAKE"


def frodo_keygen():
    kem = oqs.KeyEncapsulation(KEM_ALG)
    pk = kem.generate_keypair()
    sk = kem.export_secret_key()
    return bytes(pk), bytes(sk)


def frodo_encaps(pk: bytes):
    kem = oqs.KeyEncapsulation(KEM_ALG)
    ct, ss = kem.encap_secret(pk)
    return bytes(ct), bytes(ss)


def frodo_decaps(sk: bytes, ct: bytes):
    kem = oqs.KeyEncapsulation(KEM_ALG, secret_key=sk)
    return bytes(kem.decap_secret(ct))


# C code generator helpers

def c_bytes(data: bytes, name: str) -> str:
    hex_str = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[] = {{{hex_str}}};"


def main():
    out = []
    out.append("/* AUTO-GENERATED by gen_falcon_frodo_kat.py -- DO NOT EDIT */")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("#include <stddef.h>")
    out.append("")

    # FREE FALCON TERNARY KAT
    out.append("/* FREE FALCON TERNARY (N=1536) KAT */")
    out.append("")

    # Deterministic keygen seed
    keygen_seed = bytes(range(48))
    pk, sk = falcon_keygen(keygen_seed)

    out.append(c_bytes(keygen_seed, "FALCON_KEYGEN_SEED"))
    out.append(f"static const size_t FALCON_KEYGEN_SEED_LEN = {len(keygen_seed)};")
    out.append("")

    out.append(c_bytes(pk, "FALCON_EXPECTED_PK"))
    out.append(f"static const size_t FALCON_EXPECTED_PK_LEN = {len(pk)};")
    out.append("")

    out.append(c_bytes(sk, "FALCON_EXPECTED_SK"))
    out.append(f"static const size_t FALCON_EXPECTED_SK_LEN = {len(sk)};")
    out.append("")

    # Message 1: sign with Python -> C must verify
    msg1 = b"FREE Falcon ternary KAT test vector: message one"
    sig_seed1 = bytes([0x42] * 48)
    sig1 = falcon_sign(sig_seed1, sk, msg1)
    assert falcon_verify(pk, msg1, sig1), "self-verify msg1 failed"

    out.append(c_bytes(msg1, "FALCON_MSG1"))
    out.append(f"static const size_t FALCON_MSG1_LEN = {len(msg1)};")
    out.append(c_bytes(sig_seed1, "FALCON_SIG_SEED1"))
    out.append(c_bytes(sig1, "FALCON_SIG1"))
    out.append(f"static const size_t FALCON_SIG1_LEN = {len(sig1)};")
    out.append("")

    # Message 2: different message -> different sig -> C must verify
    msg2 = b"Second message for FREE Falcon cross-KAT: different content"
    sig_seed2 = bytes([0xBB] * 48)
    sig2 = falcon_sign(sig_seed2, sk, msg2)
    assert falcon_verify(pk, msg2, sig2), "self-verify msg2 failed"
    assert sig1 != sig2, "sigs must differ"

    out.append(c_bytes(msg2, "FALCON_MSG2"))
    out.append(f"static const size_t FALCON_MSG2_LEN = {len(msg2)};")
    out.append(c_bytes(sig_seed2, "FALCON_SIG_SEED2"))
    out.append(c_bytes(sig2, "FALCON_SIG2"))
    out.append(f"static const size_t FALCON_SIG2_LEN = {len(sig2)};")
    out.append("")

    # Message 3: empty message edge case
    msg3 = b""
    sig_seed3 = bytes([0xCC] * 48)
    sig3 = falcon_sign(sig_seed3, sk, msg3)
    assert falcon_verify(pk, msg3, sig3), "self-verify msg3 (empty) failed"

    out.append(c_bytes(sig_seed3, "FALCON_SIG_SEED3"))
    out.append(c_bytes(sig3, "FALCON_SIG3"))
    out.append(f"static const size_t FALCON_SIG3_LEN = {len(sig3)};")
    out.append("static const size_t FALCON_MSG3_LEN = 0;")
    out.append("")

    # Cross-check: wrong message must fail verify
    assert not falcon_verify(pk, b"wrong message", sig1), "verify with wrong msg should fail"

    # FRODOKEM-640-SHAKE KAT
    out.append("/* FRODOKEM-640-SHAKE KAT */")
    out.append("")

    pk_kem, sk_kem = frodo_keygen()

    out.append(c_bytes(pk_kem, "FRODO_PK"))
    out.append(f"static const size_t FRODO_PK_LEN = {len(pk_kem)};")
    out.append(c_bytes(sk_kem, "FRODO_SK"))
    out.append(f"static const size_t FRODO_SK_LEN = {len(sk_kem)};")
    out.append("")

    # Encaps 1
    ct1, ss1 = frodo_encaps(pk_kem)
    ss1_check = frodo_decaps(sk_kem, ct1)
    assert ss1 == ss1_check, "sanity: frodo ss1 mismatch"

    out.append(c_bytes(ct1, "FRODO_CT1"))
    out.append(f"static const size_t FRODO_CT1_LEN = {len(ct1)};")
    out.append(c_bytes(ss1, "FRODO_EXPECTED_SS1"))
    out.append(f"static const size_t FRODO_SS1_LEN = {len(ss1)};")
    out.append("")

    # Encaps 2
    ct2, ss2 = frodo_encaps(pk_kem)
    ss2_check = frodo_decaps(sk_kem, ct2)
    assert ss2 == ss2_check, "sanity: frodo ss2 mismatch"
    assert ct1 != ct2, "cts must differ"

    out.append(c_bytes(ct2, "FRODO_CT2"))
    out.append(f"static const size_t FRODO_CT2_LEN = {len(ct2)};")
    out.append(c_bytes(ss2, "FRODO_EXPECTED_SS2"))
    out.append(f"static const size_t FRODO_SS2_LEN = {len(ss2)};")
    out.append("")

    print("\n".join(out))


if __name__ == "__main__":
    main()
